### ISSUE TITLE
Profile images broke in pal

### ISSUE THREAD

**Issue by vegaslon** [kasenvr/Iamus#34]
Iamus no longer sending profile picture url back for self when requested from user api.

**Comment by Misterblue** [comment]
What is the field that is missing in which request?

**Comment by Misterblue** [comment]
Looking at 'pal.js', the routine getProfilePicture() goes to "METAVERSE_SERVER_URL/users/:username" and expects to get an HTML page which it regex'es to find an IMG element with the class "users-img".

The solution to this issue is to either add the new "/users/:username request (and the associated profile stuff) to the metaverse-server or fix the pal.js script to fetch the URL from /api/v1/accounts/:username/field/images_thumbnail or similar.

I'm voting for the latter. I'll look into creating a PR for Project_Athena to change pal.js.

**Comment by vegaslon** [comment]
ah that function is never called. It is actually getting profile picture from a "PAL update" before it was sending "{"sessionId":"{redacted}","userName":"Vegaslon","connection":"self","profileUrl":"https://hifi-metaverse.s3-us-west-1.amazonaws.com/images/users/previews/e36/76d/7b-/thumbnail/hifi-user-e3676d7b-6350-4495-b30c-3bfeb17711d6.png?1504609611%22,%22placeName%22:%22violet-system-8402%22%7D" now it is only sending "{"sessionId":"","userName":"vegaslon","admin":false}"

**Comment by vegaslon** [comment]
This was working 3-4 days ago. Suspect the new connection code is just being to restricting.

**Comment by Misterblue** [comment]
Another place in connectionUtils.js::getConnectionData where it build the data you are referencing and it gets the "profileUrl" data from user.images.thumbnail.  The request to the metaverse-server looks like it's /api/v1/users which, at the moment, just returns one's own profile. Will eventually return self, friends, and connections.
Is there a way to set a user's thumbnail URL on the dashboard?

**Comment by vegaslon** [comment]
Yes there is a profile tab on dashboard that will get and set all three images. Viewing them in pal was possible once you started sending connection:self before.

**Comment by Misterblue** [comment]
This should be fixed after version 2.2.20. Is this still a problem?

**Comment by vegaslon** [comment]
From what I see it has been fixed
