### ISSUE TITLE
Domain token isn't readily visible

### ISSUE THREAD

**Issue by ctrlaltdavid** [kasenvr/Iamus#5]
On the "Get Domain Token with Account" page, it can appear that nothing happens when you click the "Get Token" button. This is because the token info is put in the rectangular box underneath the dialog and not necessarily visible.

Suggestion: Put the domain token in the blank space in the dialog box, under the bottom horizontal rule.

https://i.gyazo.com/d0d47a56b0e34e072fe55e12a8e10723.jpg

**Comment by ctrlaltdavid** [comment]
Similarly, if you enter an invalid user name or password an error message (not very user friendly) is currently displayed in the rectangular box, with no other indication of login failure.

**Comment by Misterblue** [comment]
This is being "solved" by moving the domain access token generation to the Dashboard. In the future, the user will be redirected to the Dashboard rather than to the embedded web page to create the token.

**Comment by Misterblue** [comment]
This was fixed in two ways:
in the default static web page, the text was moved up and made white to be more visible;
and a server parameter was created ("metaverse-server.tokengen_url") that allows the server to specify a different web page to display. The latter can be used by the Dashboard to handle the token generation.
